### ISSUE TITLE
Error when trying to output a transaction in JSON format

### ISSUE THREAD

**Issue by luca-mayven** [onflow/flow-cli#229]
### Problem

When I try to output as JSON a transaction I get the following error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1036e1698]

goroutine 1 [running]:
github.com/onflow/flow-cli/internal/transactions.(*TransactionResult).JSON(0x14000118f30, 0x4, 0x16d1a7956)
	github.com/onflow/flow-cli/internal/transactions/transactions.go:64 +0x488
github.com/onflow/flow-cli/internal/command.formatResult(0x103d49bc8, 0x14000118f30, 0x0, 0x0, 0x16d1a7956, 0x4, 0x16d1a7956, 0x4, 0x0, 0x0)
	github.com/onflow/flow-cli/internal/command/command.go:274 +0x150
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x1046b31e0, 0x1400018e190, 0x1, 0x5)
	github.com/onflow/flow-cli/internal/command/command.go:189 +0x30c
github.com/spf13/cobra.(*Command).execute(0x1046b31e0, 0x140001c2030, 0x5, 0x5, 0x1046b31e0, 0x140001c2030)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000612b00, 0x1400048ff60, 0x1, 0x1)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x234
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	github.com/onflow/flow-cli/cmd/flow/main.go:65 +0x2d8

### Steps to Reproduce

Use any transaction that works without the "-o json" option and add it to it. When you add it it will throw that error

### Acceptance Criteria

If I'm able to use the  "-o json" option on transactions.

### Context

I'm using the latest flow-cli version on latest macOS with emulator running.

Thanks!

**Comment by sideninja** [comment]
Thank you for catching this, fixed in the next release.
