### ISSUE TITLE
flow events not working with JSON output

### ISSUE THREAD

**Issue by luca-mayven** [onflow/flow-cli#233]
### Problem

I try to listen to some events by using the following command 

`flow events get A.f8d6e0586b0a20c7.Test.Created 0 1000 -o json`

But when I do so it crashes with the following error

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/onflow/flow-cli/internal/events.(*EventResult).JSON(0x14000297e00, 0x4, 0x16f1d3955)
	github.com/onflow/flow-cli/internal/events/events.go:57 +0x184
github.com/onflow/flow-cli/internal/command.formatResult(0x101d1db08, 0x14000297e00, 0x0, 0x0, 0x16f1d3955, 0x4, 0x16f1d3955, 0x4, 0x0, 0x0)
	github.com/onflow/flow-cli/internal/command/command.go:274 +0x150
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x102684d20, 0x1400013c1e0, 0x3, 0x5)
	github.com/onflow/flow-cli/internal/command/command.go:189 +0x30c
github.com/spf13/cobra.(*Command).execute(0x102684d20, 0x140001c2030, 0x5, 0x5, 0x102684d20, 0x140001c2030)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x140001f3080, 0x1400053ff60, 0x1, 0x1)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x234
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	github.com/onflow/flow-cli/cmd/flow/main.go:65 +0x2d8
```

If I run it without "-o json" I can correctly see the events like this

```
Events Block #83:
    Index	0
    Type	A.f8d6e0586b0a20c7.Test.Created
    Tx ID	3f43ddcf57b871d5bd9c112170b6ce96d804b8f2456eec06b09b1b661235c07d
    Values
		- id (UInt64):		12
		- name (String):	test
		- url (String):		https://test.com/
```

### Steps to Reproduce

Try to listen to any event and use the "-o json" option

### Acceptance Criteria

If I'm able to listen to events and output them in JSON format

### Context

I'm using the latest flow-cli on macOS

**Comment by sideninja** [comment]
Fixed in the next release
