### ISSUE TITLE
Handle wrong emulator service account reference

### ISSUE THREAD

**Issue by uhbif19** [onflow/flow-cli#323]
### Problem

Getting segfault:

```
.venv ❯ flow accounts create         
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc7d7a6]

goroutine 1 [running]:
github.com/onflow/flow-cli/pkg/flowkit.(*Account).Address(...)
        github.com/onflow/flow-cli/pkg/flowkit/account.go:40
github.com/onflow/flow-cli/pkg/flowkit.NewCreateAccountTransaction(0x0, 0x0, 0x0, 0x0, 0xc0005c58d0, 0x0, 0x0, 0x0, 0x16d5b20, 0xc00007a070)
        github.com/onflow/flow-cli/pkg/flowkit/transaction.go:146 +0x26
github.com/onflow/flow-cli/pkg/flowkit/services.(*Accounts).Create(0xc0003ae4e0, 0x0, 0x0, 0x0, 0x0, 0x1f73328, 0x0, 0x0, 0x2, 0x3, ...)
        github.com/onflow/flow-cli/pkg/flowkit/services/accounts.go:174 +0x4ba
github.com/onflow/flow-cli/internal/accounts.create(0x1f73328, 0x0, 0x0, 0x16e5ec0, 0xc00038b680, 0x0, 0x0, 0x1416e52, 0x4, 0x0, ...)
        github.com/onflow/flow-cli/internal/accounts/create.go:89 +0x3a5
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x1f2b120, 0x1f73328, 0x0, 0x0)
        github.com/onflow/flow-cli/internal/command/command.go:116 +0x395
github.com/spf13/cobra.(*Command).execute(0x1f2b120, 0xc00003a1a0, 0x0, 0x0, 0x1f2b120, 0xc00003a1a0)
        github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f3b80, 0xc0004d9f20, 0x1, 0x1)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:69 +0x425
```

### Steps to Reproduce

Run  `flow accounts create`

### Context

```
.venv ❯ flow version  
Version: v0.25.0
Commit: 9afd7938ebf603611d7b159278a259c850e0adda
```

Was updated from some older version (0.17?) using sh script. OS is ArchLinux.

**Comment by sideninja** [comment]
Can you please share your `flow.json` with redacted secrets or reinitialize it since your previous version was so old it might have skipped a lot of deprecations and warnings and it might no longer support this older format.

**Comment by uhbif19** [comment]
@sideninja 

Ok, default config works. My config is indeed old and probably used a deprecated config variant, because earlier new (?) config format did not support some option I used.

I inserted parts of my config to see what causes error. It seems that `accounts / service / keys` causes it in some situations.

Here `service` is copied from my config, and this cause segfault:

```
"accounts": {
		"service": {
			"address": "f8d6e0586b0a20c7",
			"keys": "b3a5f387ee2a4c166f79384d819a240d5ec15e8d42dc4aef8224059360ae0c9a",
			"chain": "flow-emulator"
		},
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"key": "d7c6e6c0d9c92bb019f7b697dc3557890b8e27214fa69c915581d104582c586c"
		}
	},
```

If I remove `emulator-account` there is segfault too. But then both are `keys`  - no segfault happen.

But this causes segfault:

```
"accounts": {
		"service": {
			"address": "f8d6e0586b0a20c7",
			"keys": "b3a5f387ee2a4c166f79384d819a240d5ec15e8d42dc4aef8224059360ae0c9a",
			"chain": "flow-emulator"
		}
	},
```


Also, I just got similar segfault after regularly handled error - using already locked flow db. It seems like segfault in this situation is not correct behaviour?

```
.venv ❯ flow emulator start --persist       
INFO[0000] ⚙️   Using service account 0xf8d6e0586b0a20c7  serviceAddress=f8d6e0586b0a20c7 serviceHashAlgo=SHA3_256 servicePrivKey=809b3e7bb112ca3b933b23f549d5f2683a32053e47f1d7928e5a1c44614124ad servicePubKey=204dd65a9cdff1f27a59cfb223af70dbfebed485e45ee7540d136c701d4938a0d4270cb9b1a4b5463f7b5d53d98dab1c7ebd7eab2dbb8462638974fc413494b6 serviceSigAlgo=ECDSA_P256
ERRO[0000] ❗  Failed to configure storage                error="failed to initialize Badger store: could not open database: Cannot acquire directory lock on \"./flowdb\".  Another process is using this Badger database.: resource temporarily unavailable"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10f2ca6]

goroutine 1 [running]:
github.com/onflow/flow-emulator/server.(*EmulatorServer).Stop(0x0)
        github.com/onflow/flow-emulator@v0.22.0/server/server.go:188 +0x26
github.com/onflow/flow-emulator/server.(*EmulatorServer).Start(0x0)
        github.com/onflow/flow-emulator@v0.22.0/server/server.go:155 +0x45
github.com/onflow/flow-emulator/cmd/emulator/start.Cmd.func1(0xc000268780, 0xc0005960e0, 0x1, 0x2)
        github.com/onflow/flow-emulator@v0.22.0/cmd/emulator/start/start.go:153 +0x778
github.com/spf13/cobra.(*Command).execute(0xc000268780, 0xc000188060, 0x2, 0x2, 0xc000268780, 0xc000188060)
        github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000269180, 0xc0006c7f20, 0x1, 0x1)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:69 +0x425
```

**Comment by sideninja** [comment]
Thank you for this report. Can you share what is your config for `emulator` key because I believe the root of this problem is that you reference an account that is not in the config, but in any case, it should be handled and the error should provide an explanation.

**Comment by uhbif19** [comment]
Seems like I was incorrect in last message. Then I rename `service` account to another name - then segfault goes away.

Emulator config:

```
"emulators": {
		"default": {
			"port": 3569,
			"serviceAccount": "service"
		}
	},
```
emulator deployment:

```
"emulator": {
	"service": ["NonFungibleToken", "CheezeNFT", "CheezeMarket"]
},
```

**Comment by sideninja** [comment]
Yeah, I thought it was that. 
I will make sure this is handled and a better error message is displayed. 
Thank you for reporting.

**Comment by bjartek** [comment]
I think this will be fixed with https://github.com/onflow/flow-cli/pull/336
