### ISSUE TITLE
Remove contract bug

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-cli#333]
### Problem
If you try to remove a contract from the account in a folder where flow.json doesn't exist you get a crash.

```
flow accounts remove-contract FungibleToken --signer test -n testnet                                                                                                                       
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1027bcf40]

goroutine 1 [running]:
github.com/onflow/flow-cli/pkg/flowkit.(*Account).Address(...)
	github.com/onflow/flow-cli/pkg/flowkit/account.go:40
github.com/onflow/flow-cli/pkg/flowkit.NewRemoveAccountContractTransaction(0x0, 0x16dd979ee, 0xd, 0x1400047ede8, 0x1400066fab8, 0x102a8a5c0)
	github.com/onflow/flow-cli/pkg/flowkit/transaction.go:89 +0x20
github.com/onflow/flow-cli/pkg/flowkit/services.(*Accounts).RemoveContract(0x1400023b8c0, 0x0, 0x16dd979ee, 0xd, 0x0, 0x0, 0x0)
	github.com/onflow/flow-cli/pkg/flowkit/services/accounts.go:309 +0x54
github.com/onflow/flow-cli/internal/accounts.removeContract(0x1400009b180, 0x1, 0x5, 0x1031ea528, 0x1400023de20, 0x0, 0x0, 0x102bec043, 0x4, 0x0, ...)
	github.com/onflow/flow-cli/internal/accounts/contract-remove.go:58 +0xac
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x103a09ce0, 0x1400009b180, 0x1, 0x5)
	github.com/onflow/flow-cli/internal/command/command.go:116 +0x2fc
github.com/spf13/cobra.(*Command).execute(0x103a09ce0, 0x1400003c0b0, 0x5, 0x5, 0x103a09ce0, 0x1400003c0b0)
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000123180, 0x140004bff10, 0x1, 0x1)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()

```

**Comment by bjartek** [comment]
This error is because ByName in Accounts() does not return err when it fails and then it is easy to forget to check it.
