### ISSUE TITLE
SDK can't parse transactions with functions

### ISSUE THREAD

**Issue by KeisukeYamashita** [onflow/flow-cli#437]
### Instructions

When  I try to send a transaction with util functions like below, the CLI panics

```cadence
pub fun dummy(_ address: Address): Void {}

transaction {
  prepare(acct: AuthAccount) {}
}
```

### Problem

When I try to send the transaction, I run into this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4883510]

goroutine 1 [running]:
github.com/onflow/flow-cli/pkg/flowkit.(*Transaction).AddAuthorizers(0xc000a21488, {0xc000a1da48, 0x1, 0xc000486900})
        github.com/onflow/flow-cli/pkg/flowkit/transaction.go:294 +0x90
github.com/onflow/flow-cli/pkg/flowkit/services.(*Transactions).Build(0xc000263b00, {0xf8, 0xd6, 0xe0, 0x58, 0x6b, 0xa, 0x20, 0xc7}, {0xc000a1da48, ...}, ...)
        github.com/onflow/flow-cli/pkg/flowkit/services/transactions.go:141 +0x40a
github.com/onflow/flow-cli/pkg/flowkit/services.(*Transactions).Send(0xc000263b00, 0xc00012a9b0, {0xc000994000, 0x69f, 0x89f}, {0x7ffeefbfe77f, 0x31}, 0xc0002861f8, {0x625cad0, 0x0, ...}, ...)
        github.com/onflow/flow-cli/pkg/flowkit/services/transactions.go:220 +0x1c6
github.com/onflow/flow-cli/internal/transactions.send({0xc0000f1240, 0x2, 0x4}, {0x5695d20, 0xc000584f60}, {{0x0, 0x0}, {0x52b31d0, 0x4}, {0x0, ...}, ...}, ...)
        github.com/onflow/flow-cli/internal/transactions/send.go:89 +0x312
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x6215380, {0xc0000f1240, 0x2, 0x4})
        github.com/onflow/flow-cli/internal/command/command.go:116 +0x315
github.com/spf13/cobra.(*Command).execute(0x6215380, {0xc00003c0a0, 0x4, 0x4})
        github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003b1180)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:76 +0x465
```

#### 1. Pass ✅ 

This is okay.

```cadence
transaction {
  prepare(acct: AuthAccount) {}
}
```

#### 2.  Panics 💥 

```cadence
pub fun dummy(_ address: Address): Void {}

transaction {
  prepare(acct: AuthAccount) {}
}
```

### Acceptance Criteria

<if any>

### Context

This happens in these components

* Flow CLI
* VS Code extensions

Sorry, if this is expected behavior.
When I send the transaction directry to the API, I don't get any errors. Thus, I think this only happens in the Go SDK and the VS Code extension.

**Comment by sideninja** [comment]
Thank you for this great report, I will take a look and get back to you next week.

**Comment by sideninja** [comment]
Hey, @KeisukeYamashita sorry this is taking a bit longer, I've been super busy with REST API, I will take a look in the next few days this week.

**Comment by KeisukeYamashita** [comment]
No worries!! Thank you very much for spending time tackling this issue🙏

**Comment by sideninja** [comment]
@KeisukeYamashita sorry it took a bit longer, but it's now fixed and will be released with next release. Thank you, great catch.
