### ISSUE TITLE
Flow client crashing when deploying a project locally using `flow project deploy -n emulator`

### ISSUE THREAD

**Issue by ttruga** [onflow/flow-cli#479]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Im using the emulator in order to run and test some transactions and I keep running with the same issue, the emulator crashes when I try to deploy some base contracts located in a specific location. It started happening when I updated to the latest version of flow-cli (0.32.1).

### Steps to Reproduce

1. flow init --reset
2. Update the flow.json file in order to look like this one, the contracts to be deployed are the standard versions of NonFungibleToken, MetadataViews and NFTStorefront

```
{
  "emulators": {
    "default": {
      "port": 3569,
      "serviceAccount": "emulator-account"
    }
  },
  "contracts": {
    "NonFungibleToken": {
      "source": "./cadence/contracts/NonFungibleToken.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7"
      }
    },
    "MetadataViews": {
      "source": "./cadence/contracts/MetadataViews.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7"
      }
    },
    "NFTStorefront": {
      "source": "./cadence/contracts/NFTStorefront.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7"
      }
    }
  },
  "networks": {
    "emulator": "127.0.0.1:3569",
    "mainnet": "access.mainnet.nodes.onflow.org:9000",
    "testnet": "access.devnet.nodes.onflow.org:9000"
  },
  "accounts": {
    "emulator-account": {
      "address": "f8d6e0586b0a20c7",
      "key": "d3b0afb49e6108b98c839ca0738a145b9a3804806844743df373670d296914a7"
    }
  },
  "deployments": {
    "emulator": {
      "emulator-account": ["NonFungibleToken", "MetadataViews", "NFTStorefront"]
    }
  }
}
```

3. In a terminal run the emulator like this: 
```
% flow emulator 
```

4. In a separate terminal deploy the project: 
```
% flow project deploy -n emulator
```

Output: 

```
% flow project deploy -n emulator          
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x401546a]

goroutine 1 [running]:
runtime.throw({0x52c7694?, 0x0?})
        runtime/panic.go:992 +0x71 fp=0xc00059d348 sp=0xc00059d318 pc=0x4039ad1
runtime.sigpanic()
        runtime/signal_unix.go:825 +0x305 fp=0xc00059d398 sp=0xc00059d348 pc=0x404f205
runtime.mapiternext(0xc0001f34d0)
        runtime/map.go:913 +0x18a fp=0xc00059d408 sp=0xc00059d398 pc=0x401546a
runtime.mapiterinit(0x0?, 0x515db80?, 0xc00059d460?)
        runtime/map.go:861 +0x228 fp=0xc00059d428 sp=0xc00059d408 pc=0x4015288
reflect.mapiterinit(0x50d6680?, 0x4f53f01?, 0xc00059d4e0?)
        runtime/map.go:1373 +0x19 fp=0xc00059d450 sp=0xc00059d428 pc=0x4063eb9
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc0001f34e0)
        gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:89 +0x5e fp=0xc00059d470 sp=0xc00059d450 pc=0x4b7573e
gonum.org/v1/gonum/graph/iterator.(*Nodes).NodeSlice(0xc000860330)
        gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:69 +0x8b fp=0xc00059d4f0 sp=0xc00059d470 pc=0x4b759cb
gonum.org/v1/gonum/graph.NodesOf({0x57e5bc0, 0xc000860330})
        gonum.org/v1/gonum@v0.9.3/graph/nodes_edges.go:72 +0xb7 fp=0xc00059d570 sp=0xc00059d4f0 pc=0x4b74877
gonum.org/v1/gonum/graph/topo.tarjanSCCstabilized({0x57ebf58, 0xc0009126e0}, 0x5635490)
        gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:97 +0x4c fp=0xc00059d638 sp=0xc00059d570 pc=0x4cc9bac
gonum.org/v1/gonum/graph/topo.SortStabilized({0x57ebf58?, 0xc0009126e0?}, 0xc000912700?)
        gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:56 +0x39 fp=0xc00059d670 sp=0xc00059d638 pc=0x4cc9559
github.com/onflow/flow-cli/pkg/flowkit/contracts.sortByDeploymentOrder({0xc0009126c0, 0x3, 0xc00011b460?})
        github.com/onflow/flow-cli/pkg/flowkit/contracts/contracts.go:194 +0x23d fp=0xc00059d7a8 sp=0xc00059d670 pc=0x4ccb49d
github.com/onflow/flow-cli/pkg/flowkit/contracts.(*Preprocessor).ContractDeploymentOrder(...)
        github.com/onflow/flow-cli/pkg/flowkit/contracts/preprocessor.go:103
github.com/onflow/flow-cli/pkg/flowkit/services.(*Project).Deploy(0xc00011e4b0, {0x7ffeefbff967, 0x8}, 0x0)
        github.com/onflow/flow-cli/pkg/flowkit/services/project.go:144 +0x33b fp=0xc00059db10 sp=0xc00059d7a8 pc=0x4cd1e9b
github.com/onflow/flow-cli/internal/project.deploy({0xc000682680?, 0x0?, 0x0?}, {0x1?, 0x6010106?}, {{0x0, 0x0}, {0x52c6d32, 0x4}, {0x0, ...}, ...}, ...)
        github.com/onflow/flow-cli/internal/project/deploy.go:53 +0x38 fp=0xc00059db58 sp=0xc00059db10 pc=0x4f35a78
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x629aba0?, {0xc0009138e0, 0x0, 0x2})
        github.com/onflow/flow-cli/internal/command/command.go:124 +0x38d fp=0xc00059dcd8 sp=0xc00059db58 pc=0x4cf034d
github.com/spf13/cobra.(*Command).execute(0x629aba0, {0xc00003c0d0, 0x2, 0x2})
        github.com/spf13/cobra@v1.3.0/command.go:860 +0x663 fp=0xc00059ddb0 sp=0xc00059dcd8 pc=0x46e8b83
github.com/spf13/cobra.(*Command).ExecuteC(0xc000455b80)
        github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4 fp=0xc00059de68 sp=0xc00059ddb0 pc=0x46e9214
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:82 +0x4f5 fp=0xc00059df80 sp=0xc00059de68 pc=0x4f452d5
runtime.main()
        runtime/proc.go:250 +0x212 fp=0xc00059dfe0 sp=0xc00059df80 pc=0x403c1b2
runtime.goexit()
        runtime/asm_amd64.s:1571 +0x1 fp=0xc00059dfe8 sp=0xc00059dfe0 pc=0x406a421

goroutine 11 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000053f80)
        go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
        go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0xe805038, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000426080?, 0xc0003d0000?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000426080, {0xc0003d0000, 0x8000, 0x8000})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000426080, {0xc0003d0000?, 0x4012da5?, 0x3?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0001d4048, {0xc0003d0000?, 0x30?, 0x4010401?})
        net/net.go:183 +0x45
bufio.(*Reader).Read(0xc0001300c0, {0xc00002e120, 0x9, 0xc000900000?})
        bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x57d3860, 0xc0001300c0}, {0xc00002e120, 0x9, 0x9}, 0x9)
        io/io.go:331 +0x9a
io.ReadFull(...)
        io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc00002e120?, 0x9?, 0xc0008602a0?}, {0x57d3860?, 0xc0001300c0?})
        golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00002e0e0)
        golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc00039c000)
        google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1499 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
        google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:364 +0x17df

goroutine 40 [select]:
github.com/desertbit/timer.timerRoutine()
        github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:119 +0xba
created by github.com/desertbit/timer.init.0
        github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:15 +0x25

goroutine 16 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0001d8370, 0x1)
        google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000130120)
        google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
        google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
        google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x1e31

goroutine 42 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000910b40)
        google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
        google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:67 +0x245

goroutine 85 [IO wait]:
internal/poll.runtime_pollWait(0xe804f48, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0003de980?, 0xc0004b4000?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0003de980, {0xc0004b4000, 0x1293, 0x1293})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0003de980, {0xc0004b4000?, 0x3fffd4003fffd3?, 0xc0004357b0?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000512020, {0xc0004b4000?, 0x401ab2f?, 0xd99fa00?})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0001cdb00, {0xc0004b4000?, 0x0?, 0x34?})
        crypto/tls/conn.go:784 +0x3d
bytes.(*Buffer).ReadFrom(0xc0001d65f8, {0x57d3b00, 0xc0001cdb00})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0001d6380, {0xe5c3840?, 0xc000512020}, 0x0?)
        crypto/tls/conn.go:806 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0001d6380, 0x0)
        crypto/tls/conn.go:613 +0x116
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:581
crypto/tls.(*Conn).Read(0xc0001d6380, {0xc0004eb000, 0x1000, 0x42a0c20?})
        crypto/tls/conn.go:1284 +0x16f
bufio.(*Reader).Read(0xc000418780, {0xc0004984a0, 0x9, 0x42bd5e2?})
        bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x57d3860, 0xc000418780}, {0xc0004984a0, 0x9, 0x9}, 0x9)
        io/io.go:331 +0x9a
io.ReadFull(...)
        io/io.go:350
net/http.http2readFrameHeader({0xc0004984a0?, 0x9?, 0xc00024d260?}, {0x57d3860?, 0xc000418780?})
        net/http/h2_bundle.go:1566 +0x6e
net/http.(*http2Framer).ReadFrame(0xc000498460)
        net/http/h2_bundle.go:1830 +0x95
net/http.(*http2clientConnReadLoop).run(0xc000435f98)
        net/http/h2_bundle.go:8815 +0x130
net/http.(*http2ClientConn).readLoop(0xc000428180)
        net/http/h2_bundle.go:8711 +0x6f
created by net/http.(*http2Transport).newClientConn
        net/http/h2_bundle.go:7439 +0xa65
```

### Acceptance Criteria

To successfully deploy the contracts in the emulator so I can interact with them. 

### Context

Working on testing several transactions that enable listing, purchasing and delisting NFTs on a storefront account

In this image you can see that nothing was logged on the emulator itself after the test
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/638139/159978869-f8027269-1137-4859-8050-096d755742d4.png">

**Comment by chase1745** [comment]
Also got a similar crash deploying to testnet with the `--update` flag. Here's a gist of the error: https://gist.github.com/chase1745/3861694a222217ec3bfd04a5d20c0b5f.

**Comment by hichana** [comment]
I don't know if this warrants another issue created or not, but I'm having a similar problem. After upgrading to v0.32.1 from v0.31.2 and attempting to deploy contracts I get the following:

![Screen Shot 2022-03-24 at 10 47 49 AM](https://user-images.githubusercontent.com/8943047/160036143-e5b1597f-af26-49e8-91b3-4552e5559a02.png)

**Comment by hichana** [comment]
I don't know if this warrants another issue or not, but I'm having a similar problem of having upgraded from v0.31.2 to v0.32.1 I get the following crash reported:

![Screen Shot 2022-03-24 at 10 47 49 AM](https://user-images.githubusercontent.com/8943047/160036274-eda6109a-216c-4f03-8e4a-aa8d7b95cc0d.png)

**Comment by sideninja** [comment]
Thank you for your report. A fix for this will be released hopefully today.

**Comment by sideninja** [comment]
You can also use this command (since brew takes time) to update:
`sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v0.32.3`

**Comment by ttruga** [comment]
Worked! I was able to deploy all my base contracts!
